services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: kkm
      POSTGRES_PASSWORD: kkm
      POSTGRES_DB: kkm
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      secrets:
        - npmrc
      args:
        MODE: ${MODE}
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      PG_URL: postgresql://kkm:kkm@db:5432/kkm
      REDIS_URL: redis://redis:6379

volumes:
  db_data:
    driver: local

secrets:
  npmrc:
    file: .npmrc
